### ISSUE TITLE
Cannot build RubyMotion 'hello world' Application in XCode7-beta6 / IOS9 SDK

### ISSUE THREAD

**Issue by tuzman** [HipByte/RubyMotion#231]
I am attempting to get a head start on upgrading my app to IOS9 compatibility, but it seems that RM3.14 is not ready to work with the latest XCode-beta6 and the IOS9 SDK.    
I am using the latest developer build of OSX 10.11.   

I have confirmed this works on latest XCode 6 / IOS8.4.

Do you have any timing or update on RM support for IOS9 ?  I would be happy to help debug any issues.

This is the output of an app created by running 

`motion create test-app`

```
El-Capitan-MacBook-Pro:test-app fandordeveloper$ bundle exec rake debug=1
Provisioning Profile: Development
     Build ./build/iPhoneSimulator-9.0-Development
    Create ./build/iPhoneSimulator-9.0-Development/test-app.app/Info.plist
  Simulate ./build/iPhoneSimulator-9.0-Development/test-app.app
*** Starting simulator
2015-08-28 11:09:21.232 sim[3606:175492] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8194.5/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x101956b50>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x100110380>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

================================================================================
The application terminated. A crash report file may have been generated by the
system, use `rake crashlog' to open it. Use `rake debug=1' to restart the app
in the debugger.
================================================================================
rake aborted!
TypeError: no implicit conversion from nil to integer
/Library/RubyMotion/lib/motion/project/template/ios.rb:234:in `exit'
/Library/RubyMotion/lib/motion/project/template/ios.rb:234:in `block in <top (required)>'
Tasks: TOP => default => simulator
```

**Comment by MarkVillacampa** [comment]
This is an issue we're aware of, and will be fixed in the next version of RubyMotion:

http://hipbyte.myjetbrains.com/youtrack/issue/RM-933

Meanwhile please use the Xcode 7 beta 5.

PS: This repository is only for the open source part of RubyMotion. Next time please use either our community forums or file a private ticket with us.
