### ISSUE TITLE
Google Maps SDK pod fails to compile every time

### ISSUE THREAD

**Issue by aesmail** [HipByte/RubyMotion#234]
Hello,
I have been trying to compile google maps iOS SDK for a few months now with no clear solutions or answers.

Setup:
Gemfile:
```ruby
source 'https://rubygems.org'

gem 'rake'
gem 'cocoapods'
gem 'motion-cocoapods'
```

Pods:
```ruby
app.pods do
    pod 'GoogleMaps'
end
```
The latest version of Google Maps SDK is 1.10.5.
Mac OS X: 10.10.5
RubyMotion: 4.4 (paid license, been using it since v2 and I love it)
iOS 9.1 SDK

When I run rake, the result I get is the following:
```shell
Installing GoogleMaps (1.10.5)
Generating Pods project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
username$ rake
     Build ./build/iPhoneSimulator-8.0-Development
     Build ./Pods.xcodeproj [Pods - Release]
   Compile ./Target Support Files/Pods/Pods-dummy.m
   Compile ./Target Support Files/Pods/Pods-dummy.m
      Link ./Users/username/Desktop/my_maps/vendor/build/Pods.build/Release-iphonesimulator/Pods.build/Objects-normal/i386/libPods.a
      Link ./Users/username/Desktop/my_maps/vendor/build/Pods.build/Release-iphonesimulator/Pods.build/Objects-normal/x86_64/libPods.a
    ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.
```
This is the case if GoogleMaps is the only pod in Rakefile.
If I add another pod, e.g.:
```ruby
app.pods do
    pod 'GoogleMaps'
    pod 'MBProgressHUD'
end
```
The other pod does compile fine, but then I get a different error:
```shell
...
...
duplicate symbol __ZN7gmscore8renderer15GLScopedContextD1Ev in:
    ./vendor/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/GoogleMaps(GLScopedContext.o)
duplicate symbol __ZN7gmscore8renderer15GLScopedContextD2Ev in:
    ./vendor/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/GoogleMaps(GLScopedContext.o)
ld: 706 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Library/RubyMotion/lib/motion/project/builder.rb:357:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
```

Running the command again with --trace, I get:
```shell
...
...
duplicate symbol __ZN7gmscore8renderer15GLScopedContextD2Ev in:
    ./vendor/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/GoogleMaps(GLScopedContext.o)
ld: 706 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
/Library/RubyMotion/lib/motion/project/builder.rb:357:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/motion-cocoapods-1.7.4/lib/motion/project/cocoapods.rb:53:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Library/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/username/.rbenv/versions/2.2.3/bin/rake:33:in `<main>'
Tasks: TOP => build:simulator
username$
```

I really tried everything I came across but nothing fixed this problem.
I also used GoogleMaps version 1.9.2 a few months ago and it worked (compiled fine) but I remember it gave me tons of errors when submitting to iTunesConnect that I gave up on it later.

I am currently building the app using Xcode and Objective-C with no problems, but I am willing to move the code to RubyMotion as soon as I find a working solution (or even a workaround).

I hope I included all necessary information for this issue.
I love RubyMotion so much and thank you guys for all the hard work you're doing.

**Comment by aesmail** [comment]
I found hipbyte/motion-cocoapods#124 which was created 3 days ago and might be the solution to this problem.
